// Labelled examples the scorer is trained on: [title, category the user picked, minutes, score 0–100].
// Scores follow one rubric: E < 25, D 25–39, C 40–54, B 55–69, A 70–84, S 85+.
// They reflect effort and difficulty together — a long, hard, active task scores highest;
// short, easy or leisure tasks score lowest. Add cases and run `npm run scorer:train`.

import type { Category } from "../quests.ts";

export type Example = [title: string, category: Category, minutes: number, score: number];

export const EXAMPLES: Example[] = [
  // ---------- University: exams and exam prep ----------
  ["Models of Computation final exam", "study", 180, 95],
  ["COMP30026 exam", "study", 120, 90],
  ["Linear algebra midterm", "study", 90, 80],
  ["Calc 2 midterm", "study", 90, 78],
  ["Organic chemistry final", "study", 180, 94],
  ["Intro to psychology exam", "study", 120, 62],
  ["Microeconomics midterm", "study", 90, 66],
  ["Quantum mechanics exam", "study", 180, 96],
  ["History of art exam", "study", 120, 56],
  ["Contract law exam", "study", 180, 85],
  ["MoC past paper", "study", 120, 80],
  ["Past papers for discrete maths", "study", 150, 78],
  ["Practice exam - data structures", "study", 120, 72],
  ["Cram for biochem final", "study", 180, 82],
  ["Stats exam prep", "study", 120, 64],
  ["Exam revision: algorithms", "study", 120, 70],
  ["Physics 1 practice test", "study", 60, 52],
  ["Accounting exam prep", "study", 90, 55],
  ["Revise for econometrics exam", "study", 120, 74],
  ["Sample exam real analysis", "study", 120, 85],

  // ---------- University: assessments ----------
  ["Models of Computation assignment 2", "study", 180, 86],
  ["COMP30026 ass 1", "study", 120, 76],
  ["Graphics and Interaction assignment", "study", 180, 78],
  ["IT project sprint deliverable", "study", 180, 66],
  ["Machine learning project report", "study", 180, 80],
  ["Philosophy essay on Kant", "study", 180, 68],
  ["Sociology essay draft", "study", 120, 50],
  ["Lab report chemistry", "study", 120, 58],
  ["Write thesis chapter 3", "study", 240, 90],
  ["Literature review for dissertation", "study", 180, 80],
  ["Marketing group project presentation", "study", 90, 45],
  ["Finance case study", "study", 120, 55],
  ["Database systems assignment", "study", 150, 62],
  ["Compilers assignment - type checker", "study", 240, 94],
  ["Research proposal draft", "study", 120, 58],
  ["Software engineering group project", "study", 180, 62],
  ["Legal research memo", "study", 150, 68],
  ["Operating systems project threads", "study", 240, 88],
  ["Econ essay due tomorrow", "study", 180, 66],
  ["History essay 2000 words", "study", 180, 58],

  // ---------- University: problems, tutorials, labs ----------
  ["Linear algebra problem set 4", "study", 120, 70],
  ["Eigenvalues practice questions", "study", 90, 62],
  ["Pumping lemma proofs", "study", 90, 74],
  ["Turing machine exercises", "study", 90, 72],
  ["Calc 3 homework", "study", 90, 64],
  ["Physics tute questions", "study", 60, 46],
  ["Stats tutorial sheet", "study", 60, 40],
  ["Chem lab", "study", 180, 52],
  ["Organic chem mechanisms practice", "study", 90, 66],
  ["Dynamic programming leetcode", "study", 60, 50],
  ["MoC tute", "study", 60, 55],
  ["Micro workshop questions", "study", 60, 38],
  ["Differential equations pset", "study", 150, 76],
  ["Accounting journal entries exercises", "study", 60, 34],
  ["Solve Gaussian elimination problems", "study", 60, 52],
  ["Haskell exercises", "study", 90, 58],
  ["Circuit analysis homework", "study", 120, 66],
  ["Thermo problem set", "study", 120, 68],
  ["Anatomy lab practical", "study", 120, 50],
  ["Group theory proofs", "study", 120, 82],

  // ---------- University: classes ----------
  ["Models of Computation lecture", "study", 60, 42],
  ["MoC lectures", "study", 120, 52],
  ["Graphics and Interactions lecture", "study", 60, 35],
  ["Intro to economics lecture", "study", 60, 28],
  ["Psych lecture", "study", 60, 28],
  ["Watch recorded lectures for algorithms", "study", 120, 44],
  ["Catch up on 3 lectures", "study", 180, 52],
  ["Attend biology seminar", "study", 60, 24],
  ["Quantum lecture", "study", 90, 52],
  ["Philosophy tutorial class", "study", 60, 30],
  ["Law seminar", "study", 120, 38],
  ["Lec 7 linear algebra", "study", 60, 38],
  ["COMP10001 lecture", "study", 60, 28],
  ["Organic chemistry lectures weeks 3-4", "study", 120, 56],
  ["History lecture", "study", 60, 24],

  // ---------- University: study sessions and light study ----------
  ["Study for linear algebra", "study", 120, 60],
  ["Revise automata theory", "study", 120, 70],
  ["Learn regular expressions and DFAs", "study", 90, 58],
  ["Go over calculus notes", "study", 60, 40],
  ["Krebs cycle flashcards", "study", 30, 24],
  ["Anki - pharmacology", "study", 45, 34],
  ["Make notes on thermodynamics", "study", 60, 40],
  ["Read chapter 5 microeconomics", "study", 60, 32],
  ["Readings for sociology", "study", 90, 32],
  ["Review lecture slides", "study", 45, 24],
  ["Summarise contract law cases", "study", 90, 50],
  ["Skim textbook chapter", "study", 30, 10],
  ["Quizlet vocab", "study", 20, 12],
  ["Review notes quantum", "study", 60, 46],
  ["Study session with friends - stats", "study", 120, 46],
  ["Rewrite notes biology", "study", 60, 30],
  ["Watch Khan Academy videos on integrals", "study", 45, 30],
  ["Study", "study", 60, 32],
  ["Revision", "study", 120, 44],
  ["Readings", "study", 60, 24],

  // ---------- High school ----------
  ["Year 12 chemistry SAC", "study", 90, 66],
  ["VCE Methods practice exam", "study", 150, 74],
  ["Specialist maths homework", "study", 60, 50],
  ["Year 9 maths homework", "study", 45, 22],
  ["Year 10 science test", "study", 60, 34],
  ["GCSE English essay", "study", 90, 40],
  ["A level maths past paper", "study", 120, 68],
  ["IB HL maths IA", "study", 180, 74],
  ["IB extended essay", "study", 240, 76],
  ["AP Bio unit 3 test", "study", 60, 48],
  ["AP Calculus BC practice test", "study", 120, 70],
  ["APUSH reading", "study", 60, 30],
  ["Year 11 physics projectile motion questions", "study", 60, 44],
  ["Grade 8 history worksheet", "study", 30, 16],
  ["Photosynthesis notes", "study", 30, 20],
  ["Macbeth essay plan", "study", 60, 34],
  ["Text response essay practice", "study", 90, 44],
  ["HSC English trial exam", "study", 120, 60],
  ["French vocab test", "study", 30, 22],
  ["Spanish oral exam practice", "study", 45, 34],
  ["Year 12 English practice essay", "study", 60, 42],
  ["Chem titration lab report", "study", 90, 46],
  ["Maths homework", "study", 45, 20],
  ["Science project poster", "study", 90, 30],
  ["SAT practice test", "study", 180, 70],
  ["Study for biology test", "study", 60, 32],
  ["Algebra worksheet", "study", 30, 16],
  ["Trig questions", "study", 45, 26],
  ["Geography fieldwork report", "study", 120, 40],
  ["Legal studies essay", "study", 90, 44],
  ["Japanese kanji practice", "study", 30, 18],
  ["Year 12 methods SAC", "study", 90, 70],
  ["Quadratics homework", "study", 45, 24],
  ["Business studies assignment", "study", 90, 38],
  ["PE theory homework", "study", 30, 10],
  ["Music theory practice", "study", 30, 18],
  ["Drama monologue rehearsal", "study", 45, 20],
  ["Art folio", "study", 120, 32],
  ["Year 7 spelling test", "study", 20, 5],
  ["HSC chemistry past paper", "study", 120, 66],

  // ---------- Topic-only titles ----------
  ["Eigenvectors", "study", 60, 46],
  ["Integration by parts", "study", 60, 44],
  ["Mitosis and meiosis", "study", 45, 28],
  ["Supply and demand graphs", "study", 45, 26],
  ["Dijkstra", "study", 60, 44],
  ["SN1 SN2 reactions", "study", 60, 50],
  ["World War 1 causes", "study", 45, 26],
  ["Newton's laws problems", "study", 60, 38],
  ["Recursion practice", "study", 60, 40],
  ["Hypothesis testing", "study", 60, 36],
  ["Context free grammars", "study", 90, 62],
  ["Balance sheet", "study", 45, 24],
  ["Maxwell's equations", "study", 90, 66],
  ["Shakespeare sonnets", "study", 45, 24],
  ["Big O notation", "study", 45, 34],
  ["Gas laws", "study", 45, 24],
  ["Punnett squares", "study", 30, 18],
  ["Cold war sources", "study", 60, 30],
  ["Laplace transforms", "study", 90, 64],
  ["Stoichiometry", "study", 45, 28],

  // ---------- Just a subject name ----------
  ["Geography subject", "study", 60, 30],
  ["Geography", "study", 60, 30],
  ["History", "study", 60, 30],
  ["Biology", "study", 60, 34],
  ["Calculus", "study", 60, 48],
  ["Models of Computation", "study", 60, 55],
  ["Organic chemistry", "study", 90, 62],
  ["English", "study", 60, 28],
  ["Economics unit 3", "study", 60, 36],
  ["Psychology subject review", "study", 60, 30],
  ["Physics", "study", 90, 48],
  ["Legal studies", "study", 60, 28],
  ["Music theory", "study", 45, 24],
  ["Japanese", "study", 30, 20],
  ["Year 12 geography", "study", 60, 34],
  ["Uni subject", "study", 60, 32],
  ["Study for geography", "study", 60, 32],
  ["Linear algebra topic 4", "study", 90, 58],

  // ---------- Mixed signals ----------
  ["Calculus with friends", "study", 120, 46],
  ["Study with friends for chemistry", "study", 120, 44],
  ["Biology coffee study session", "study", 60, 30],
  ["Run through physics notes", "study", 60, 36],
  ["Graphics and Interactions leg day", "gym", 90, 64],
  ["Economics lecture then gym", "study", 90, 34],

  // ---------- Typos, abbreviations, plurals ----------
  ["lecutre", "study", 60, 24],
  ["asignment", "study", 120, 50],
  ["homwork", "study", 60, 32],
  ["calc hw", "study", 60, 44],
  ["LA pset", "study", 90, 52],
  ["orgo exam", "study", 120, 84],
  ["chem tute", "study", 60, 36],
  ["econ readings", "study", 60, 28],
  ["cs assignments", "study", 180, 60],
  ["physics labs", "study", 120, 46],

  // ---------- Personal projects ----------
  ["Build portfolio website", "other", 180, 64],
  ["Portfolio site - add projects page", "other", 120, 48],
  ["Fix navbar bug on portfolio", "other", 60, 34],
  ["Deploy app to Vercel", "other", 60, 38],
  ["Build Chrome extension", "other", 240, 76],
  ["Side project: React Native app", "other", 180, 68],
  ["Refactor backend API", "other", 120, 56],
  ["Set up database schema", "other", 90, 46],
  ["Hackathon", "other", 480, 92],
  ["Code gamified study app", "other", 180, 64],
  ["Design logo for side project", "other", 60, 28],
  ["Figma mockups for app", "other", 90, 38],
  ["Wireframes for landing page", "other", 60, 30],
  ["Brainstorm project ideas", "other", 30, 12],
  ["Write README", "other", 30, 14],
  ["Blog post about my project", "other", 90, 34],
  ["Edit YouTube video", "other", 120, 38],
  ["Implement login feature", "other", 120, 54],
  ["Train ML model for side project", "other", 180, 72],
  ["Open source contribution", "other", 120, 52],
  ["Personal project", "other", 120, 44],
  ["Update portfolio", "other", 60, 26],
  ["Build discord bot", "other", 120, 50],
  ["Unity game prototype", "other", 180, 64],
  ["Learn Next.js for side project", "other", 90, 38],
  ["Project roadmap", "other", 30, 14],
  ["Write documentation", "other", 60, 24],
  ["Fix bugs", "other", 60, 32],
  ["Launch app", "other", 120, 50],
  ["Automation script for spreadsheets", "other", 60, 34],

  // ---------- Career ----------
  ["Update resume", "other", 60, 28],
  ["Write cover letter", "other", 60, 34],
  ["Apply for internships", "other", 120, 44],
  ["Grad job applications", "other", 180, 54],
  ["Interview prep", "other", 120, 52],
  ["Mock interview", "other", 60, 40],
  ["Coding interview practice", "other", 90, 56],
  ["Update LinkedIn", "other", 30, 12],
  ["Career fair", "other", 120, 24],
  ["Networking event", "other", 120, 22],

  // ---------- Work ----------
  ["Work shift", "other", 240, 46],
  ["Retail shift", "other", 300, 50],
  ["Team meeting", "other", 60, 16],
  ["Tutoring session", "other", 60, 30],
  ["Client meeting", "other", 60, 22],
  ["Work report", "other", 120, 44],
  ["Babysitting", "other", 180, 26],
  ["Casual shift at cafe", "other", 240, 44],

  // ---------- Fitness ----------
  ["Leg day", "gym", 90, 64],
  ["Push day", "gym", 75, 50],
  ["Pull day", "gym", 75, 50],
  ["Gym", "gym", 60, 42],
  ["Upper body workout", "gym", 60, 44],
  ["Full body workout", "gym", 60, 48],
  ["Deadlifts", "gym", 60, 58],
  ["Heavy squats", "gym", 60, 62],
  ["HIIT", "gym", 30, 44],
  ["5k run", "gym", 30, 40],
  ["10k run", "gym", 60, 60],
  ["Half marathon", "gym", 120, 86],
  ["Marathon", "gym", 240, 97],
  ["Long run", "gym", 90, 64],
  ["Swim laps", "gym", 45, 40],
  ["Football training", "gym", 90, 48],
  ["Basketball", "gym", 60, 40],
  ["Tennis", "gym", 60, 36],
  ["Bouldering", "gym", 90, 44],
  ["BJJ class", "gym", 90, 56],
  ["Boxing", "gym", 60, 50],
  ["Cycling", "gym", 90, 46],
  ["Hike", "gym", 180, 50],
  ["Yoga", "gym", 45, 20],
  ["Stretching", "gym", 15, 6],
  ["Walk", "gym", 30, 10],
  ["Evening walk", "personal", 45, 12],
  ["Mobility routine", "gym", 20, 8],
  ["Pilates", "gym", 45, 24],
  ["Abs workout", "gym", 20, 20],
  ["Quick workout", "gym", 20, 18],
  ["Crossfit", "gym", 60, 62],
  ["Sprints", "gym", 30, 50],
  ["Arm day", "gym", 60, 40],
  ["Chest day", "gym", 60, 46],
  ["Light jog", "gym", 20, 12],
  ["Dance class", "gym", 60, 32],
  ["Rowing", "gym", 45, 44],
  ["Push ups", "gym", 10, 6],
  ["Surfing", "gym", 120, 42],

  // ---------- Chores ----------
  ["Laundry", "chores", 30, 10],
  ["Do the dishes", "chores", 15, 6],
  ["Vacuum", "chores", 30, 10],
  ["Clean room", "chores", 45, 14],
  ["Deep clean the house", "chores", 180, 42],
  ["Meal prep", "chores", 120, 32],
  ["Cook dinner", "chores", 60, 16],
  ["Take out the bins", "chores", 10, 2],
  ["Ironing", "chores", 30, 10],
  ["Clean bathroom", "chores", 45, 18],
  ["Declutter wardrobe", "chores", 90, 28],
  ["Mow the lawn", "chores", 60, 24],
  ["Move house", "chores", 360, 66],
  ["Pack for move", "chores", 180, 36],
  ["Water plants", "chores", 10, 2],
  ["Make bed", "chores", 5, 0],
  ["Wash car", "chores", 45, 16],
  ["Clean kitchen", "chores", 30, 12],
  ["Assemble IKEA furniture", "chores", 120, 34],
  ["Chores", "chores", 60, 16],
  ["Walk the dog", "chores", 30, 8],
  ["Tidy desk", "chores", 15, 4],

  // ---------- Errands ----------
  ["Groceries", "chores", 60, 12],
  ["Grocery shopping", "chores", 45, 10],
  ["Post office", "chores", 30, 6],
  ["Renew passport", "other", 60, 22],
  ["Dentist appointment", "other", 60, 16],
  ["Doctor appointment", "other", 45, 12],
  ["Haircut", "personal", 45, 5],
  ["Pick up parcel", "chores", 20, 4],
  ["Car service", "other", 60, 12],
  ["Bank", "other", 30, 8],
  ["Pharmacy", "chores", 20, 4],
  ["Blood test", "other", 30, 10],

  // ---------- Admin ----------
  ["Reply to emails", "other", 30, 10],
  ["Emails", "other", 45, 12],
  ["Plan my week", "other", 30, 12],
  ["Weekly review", "other", 45, 16],
  ["Budget", "other", 60, 20],
  ["Tax return", "other", 120, 40],
  ["Enrol in subjects", "other", 60, 20],
  ["Pay bills", "other", 20, 6],
  ["Book flights", "other", 45, 12],
  ["Fill in forms", "other", 30, 10],
  ["Organise files", "other", 45, 12],
  ["Timetable planning", "other", 45, 16],

  // ---------- Social ----------
  ["Meet friends for coffee", "personal", 60, 6],
  ["Coffee with Sam", "personal", 60, 5],
  ["Hang out with friends", "personal", 180, 8],
  ["Dinner with family", "personal", 120, 8],
  ["Call mum", "personal", 30, 5],
  ["Birthday party", "personal", 180, 10],
  ["Date night", "personal", 180, 8],
  ["Visit grandma", "personal", 120, 12],
  ["Game night", "personal", 180, 6],
  ["Catch up with friends", "personal", 120, 7],
  ["Brunch", "personal", 90, 5],
  ["Party", "personal", 240, 8],
  ["Facetime family", "personal", 30, 5],
  ["BBQ at Tom's", "personal", 180, 7],
  ["Wedding", "personal", 360, 16],

  // ---------- Self-care ----------
  ["Meditate", "personal", 15, 6],
  ["Journal", "personal", 20, 8],
  ["Therapy session", "personal", 60, 22],
  ["Nap", "personal", 30, 0],
  ["Skincare", "personal", 15, 2],
  ["Sleep early", "personal", 30, 4],
  ["Mindfulness", "personal", 20, 6],
  ["Relax", "personal", 60, 2],
  ["Self care evening", "personal", 90, 5],
  ["Gratitude journal", "personal", 10, 5],

  // ---------- Hobbies and leisure ----------
  ["Guitar practice", "personal", 60, 28],
  ["Piano practice", "personal", 45, 26],
  ["Violin scales", "personal", 30, 20],
  ["Drawing", "personal", 60, 22],
  ["Digital art commission", "personal", 180, 44],
  ["Painting", "personal", 90, 26],
  ["Chess practice", "personal", 60, 22],
  ["Knitting", "personal", 60, 12],
  ["Baking", "personal", 90, 18],
  ["Photography walk", "personal", 90, 16],
  ["Write short story", "personal", 90, 34],
  ["Read a novel", "personal", 60, 8],
  ["Watch a movie", "personal", 120, 2],
  ["Netflix", "personal", 60, 0],
  ["Gaming", "personal", 120, 2],
  ["Board games", "personal", 90, 4],
  ["Podcast", "personal", 45, 3],
  ["Sing practice", "personal", 30, 16],
  ["Learn a song on guitar", "personal", 60, 30],
  ["Pottery class", "personal", 120, 22],

  // ---------- Vague and mixed ----------
  ["Work on stuff", "other", 60, 22],
  ["Misc", "other", 30, 10],
  ["Errands", "chores", 60, 12],
  ["Project work", "study", 120, 48],
  ["Assignment", "study", 120, 52],
  ["Essay", "study", 120, 48],
  ["Homework", "study", 60, 32],
  ["Exam", "study", 120, 70],
  ["Lecture", "study", 60, 26],
  ["Tutorial", "study", 60, 32],
  ["Read", "personal", 30, 8],
  ["Clean", "chores", 30, 10],
  ["Training", "gym", 60, 42],
  ["Practice", "personal", 60, 22],
  ["Meeting", "other", 60, 16],
];
