// Shared by extension-config.mjs and package-extension.mjs.
import { existsSync, readFileSync } from "node:fs";

export const DEFAULT_APP_URL = "https://questlog-lake.vercel.app";

/** Supabase settings from the environment (Vercel builds) or .env.local (local builds). */
export function loadSupabaseEnv() {
  const envFile = new URL("../.env.local", import.meta.url);
  const local = existsSync(envFile)
    ? Object.fromEntries(
        readFileSync(envFile, "utf8")
          .replace(/^﻿/, "")
          .split(/\r?\n/)
          .filter((line) => /^[A-Z_]+=/.test(line))
          .map((line) => [line.slice(0, line.indexOf("=")), line.slice(line.indexOf("=") + 1).trim()]),
      )
    : {};
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL || local.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || local.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
  if (!url || !key) {
    throw new Error("NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY must be set");
  }
  return { url, key };
}

/** Contents of extension/config.js. The publishable key is safe to ship (it's public by design). */
export function configSource({ url, key, appUrl }) {
  return `// Generated by scripts/extension-config.mjs. Do not edit by hand.
export const SUPABASE_URL = ${JSON.stringify(url)};
export const SUPABASE_KEY = ${JSON.stringify(key)};
export const APP_URL = ${JSON.stringify(appUrl)};
`;
}
