// Writes extension/config.js from .env.local so the extension talks to the same Supabase project.
// Usage: npm run extension:config [-- --app-url http://localhost:3000]
import { readFileSync, writeFileSync } from "node:fs";

const env = Object.fromEntries(
  readFileSync(new URL("../.env.local", import.meta.url), "utf8")
    .replace(/^﻿/, "")
    .split(/\r?\n/)
    .filter((line) => /^[A-Z_]+=/.test(line))
    .map((line) => [line.slice(0, line.indexOf("=")), line.slice(line.indexOf("=") + 1).trim()]),
);

const url = env.NEXT_PUBLIC_SUPABASE_URL;
const key = env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
if (!url || !key) {
  console.error("NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY must be set in .env.local");
  process.exit(1);
}

const appUrlFlag = process.argv.indexOf("--app-url");
const appUrl = appUrlFlag === -1 ? "https://questlog-lake.vercel.app" : process.argv[appUrlFlag + 1];

writeFileSync(
  new URL("../extension/config.js", import.meta.url),
  `// Generated by scripts/extension-config.mjs. Do not edit by hand.
export const SUPABASE_URL = ${JSON.stringify(url)};
export const SUPABASE_KEY = ${JSON.stringify(key)};
export const APP_URL = ${JSON.stringify(appUrl)};
`,
);
console.log(`Wrote extension/config.js (app: ${appUrl})`);
